Repository keepers-team/webtlo, pull requests merged in 2023-01, with the labels that each got.

#177 Exclude empty sections from selector
  php/actions/get_list_subsections.php
Labels: Type: Enhancement, Priority: Low, Component: Backend, Status: In progress

#178 add new filter by topic_id
  index.php
  php/actions/get_filtered_list_topics.php
Labels: P: Low, C: UI, T: New feature

#180 migrate get_report_hashes to individual endpoint
  php/actions/get_reports.php
  php/actions/get_reports_hashes.php
  scripts/jquery.common.js
  scripts/jquery.topics.js
Labels: T: Enhancement, P: Low, C: Backend

#181 fix control peers calculation with empty string value
  php/common/control.php
  scripts/jquery.widgets.js
Labels: T: Bug, C: Backend, P: Medium

#199 Replace outdated configuration in htaccess
  .htaccess
Labels: T: Bug, P: High, C: Distribution

#196 add simple click-ctrlclick reset-restore logic
  index.php
  scripts/jquery.topics.js
Labels: T: Enhancement, C: UI, P: Medium

#204 Fix unregistered topics search
  php/actions/get_filtered_list_topics.php
  php/common/tor_clients.php
Labels: T: Bug, C: Backend, P: Medium

#208 remove spaces from filter_phrase
  php/actions/get_filtered_list_topics.php
Labels: T: Enhancement, P: Low, C: Backend

#207 add title to topics and keepers bullets
  php/actions/get_filtered_list_topics.php
Labels: T: Enhancement, C: UI, P: Medium
