Repository keepers-team/webtlo, pull requests merged in 2025-05, with the labels that each got.

#445 Clients. Fix transmission auth token update
  src/back/Clients/Transmission.php
Labels: T: Bug, C: Clients, P: Medium

#456 Удалены ненужная таблица и триггер
  src/back/DB.php
  src/sql/0015-drop-unused-tables.sql
  src/sql/9999-init-database.sql
Labels: P: Low, C: Backend, T: Maintenance

#458 Обработка ограничений доступа к API для кандидатов в хранители
  src/back/Action/SendKeeperReports.php
  src/back/Data/KeeperPermissions.php
  src/back/External/ApiReportClient.php
  src/back/Module/Report/SendReport.php
  src/back/Update/KeepersReports.php
  src/back/Update/Subsections.php
Labels: T: Enhancement, C: Backend, P: High

#451 API concurrency value can be set in the .ini file so that it is now possible to decrease it to reduce triggering of the rate limiter
  src/back/Config/ApiForumConnect.php
  src/back/Config/ConfigServiceProvider.php
Labels: T: Enhancement, P: Low, C: Backend
